/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package S3E7P1;

import java.util.Scanner;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class GiaoVien_UI extends javax.swing.JFrame {

    Vector vtb_header = new Vector();
    Vector vtb_content = new Vector();
    DefaultTableModel dtm = new DefaultTableModel();
    GiaoVien[] lgv = new GiaoVien[100];
    int k = 0;//số phần tử giáo viên hiện có
    /**
     * Creates new form GiaoVien_UI
     */
    public GiaoVien_UI() {
        initComponents();
        vtb_header.add("Mã giáo viên");
        vtb_header.add("Tên giáo viên");
        vtb_header.add("Địa chỉ");
        vtb_header.add("Hệ số lương");
        dtm.setDataVector(vtb_content, vtb_header);
        tb_giaovien.setModel(dtm);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_ma = new javax.swing.JTextField();
        txt_ten = new javax.swing.JTextField();
        txt_dc = new javax.swing.JTextField();
        txt_hsl = new javax.swing.JTextField();
        bt_them = new javax.swing.JButton();
        bt_xoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_giaovien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giao Vien UI");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText(" Mã giáo viên:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Tên:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Địa chỉ :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Hệ số lương :");

        txt_ma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txt_ten.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txt_dc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txt_hsl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        bt_them.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_them.setText("Thêm giáo viên");
        bt_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_themActionPerformed(evt);
            }
        });

        bt_xoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_xoa.setText("Xóa");
        bt_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xoaActionPerformed(evt);
            }
        });

        tb_giaovien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tb_giaovien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_giaovien.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tb_giaovien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_giaovienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_giaovien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_them)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_xoa)
                        .addGap(252, 252, 252))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ten)
                            .addComponent(txt_hsl)
                            .addComponent(txt_ma)
                            .addComponent(txt_dc))))
                .addGap(295, 295, 295))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_dc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_hsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_them)
                    .addComponent(bt_xoa))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_themActionPerformed
        // TODO add your handling code here:
        if(txt_ma.getText().equals("") && txt_ten.getText().equals("") && txt_dc.getText().equals("") && txt_hsl.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Hãy nhập giá trị trước khi thêm","Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
        GiaoVien gv = new GiaoVien( txt_ma.getText(),txt_ten.getText(),txt_dc.getText(),Double.parseDouble(txt_hsl.getText()));
        lgv[k] = gv;
        //tạo record chứa thông tin mỗi giáo viên trong mảng
        Vector vtb_record = new Vector();
        vtb_record.add(lgv[k].getMaGV());
        vtb_record.add(lgv[k].getHoTen());
        vtb_record.add(lgv[k].getDiaChi());
        vtb_record.add(lgv[k].getHeSoLuong());
        k++;
        //table chứa header và content,content chứa nhiều record,mỗi record chứa các trường 
        vtb_content.add(vtb_record);
        dtm.setDataVector(vtb_content, vtb_header);
        tb_giaovien.setModel(dtm);
        }
        
       
        
       
        
    }//GEN-LAST:event_bt_themActionPerformed

    private void tb_giaovienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_giaovienMouseClicked
        // TODO add your handling code here:
        txt_ma.setText(tb_giaovien.getValueAt(tb_giaovien.getSelectedRow(),0).toString());
        txt_ten.setText(tb_giaovien.getValueAt(tb_giaovien.getSelectedRow(),1).toString());
        txt_dc.setText(tb_giaovien.getValueAt(tb_giaovien.getSelectedRow(),2).toString());
        txt_hsl.setText(tb_giaovien.getValueAt(tb_giaovien.getSelectedRow(),3).toString());
        
    }//GEN-LAST:event_tb_giaovienMouseClicked

    private void bt_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xoaActionPerformed
        // TODO add your handling code here:
        int deleteIndexRow = tb_giaovien.getSelectedRow();
        for(int i = deleteIndexRow;i < k - 1;i++ )
        {
            lgv[i] = lgv[i + 1];
        }
        k--;
        if(tb_giaovien.getRowCount() == 0)
        {
            JOptionPane.showMessageDialog(this,"Bảng rỗng không thể xóa","Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            dtm.removeRow(deleteIndexRow);
            tb_giaovien.setModel(dtm);
        }
        txt_ma.setText("");
        txt_ten.setText("");
        txt_dc.setText("");
        txt_hsl.setText("");
    }//GEN-LAST:event_bt_xoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoVien_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoVien_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoVien_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoVien_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoVien_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_them;
    private javax.swing.JButton bt_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_giaovien;
    private javax.swing.JTextField txt_dc;
    private javax.swing.JTextField txt_hsl;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_ten;
    // End of variables declaration//GEN-END:variables
}
