/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package S3E3P1;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class PhanSo_UI extends javax.swing.JFrame {

    /**
     * Creates new form PhanSo_UI
     */
    public PhanSo_UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_ts = new javax.swing.JTextField();
        txt_ms = new javax.swing.JTextField();
        bt_rg = new javax.swing.JButton();
        bt_tinh = new javax.swing.JButton();
        lb_kq = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phân số UI");
        setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Nhập tử số : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Nhập mẫu số :");

        txt_ts.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txt_ms.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        bt_rg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_rg.setText("Rút gọn");
        bt_rg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rgActionPerformed(evt);
            }
        });

        bt_tinh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_tinh.setText("Tính giá trị phân số");
        bt_tinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tinhActionPerformed(evt);
            }
        });

        lb_kq.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_kq.setText("Kết quả :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_kq)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(bt_rg)
                            .addComponent(jLabel1))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_tinh)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(txt_ts)
                                    .addComponent(txt_ms))
                                .addGap(5, 5, 5)))))
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_ms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_rg)
                    .addComponent(bt_tinh))
                .addGap(53, 53, 53)
                .addComponent(lb_kq)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_rgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rgActionPerformed
        // TODO add your handling code here:
        String a = txt_ts.getText();
        String b = txt_ms.getText();
        
        PhanSo ps = new PhanSo();
        if (ps.KiemTra(a) && ps.KiemTra(b))
        {
            if(Integer.parseInt(b) == 0)
            {
                 JOptionPane.showMessageDialog(this,"mẫu số phải khác 0","Error",JOptionPane.ERROR_MESSAGE);
            }
             
            else
            {
                  ps = new PhanSo(Integer.parseInt(a),Integer.parseInt(b));
                  lb_kq.setText("Kết quả :  "+ ps.rutgon());
            }        
        }
        else
        {   
            JOptionPane.showMessageDialog(this,"Nhập sai rồi","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_rgActionPerformed

    private void bt_tinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tinhActionPerformed
        // TODO add your handling code here:
        String a = txt_ts.getText();
        String b = txt_ms.getText();
        
        PhanSo ps = new PhanSo();
        if (ps.KiemTra(a) && ps.KiemTra(b))
        {
            if(Integer.parseInt(b) == 0)
            {
                 JOptionPane.showMessageDialog(this,"mẫu số phải khác 0","Error",JOptionPane.ERROR_MESSAGE);
            }
             
            else
            {
                  ps = new PhanSo(Integer.parseInt(a),Integer.parseInt(b));
                  lb_kq.setText("Kết quả :  "+ ps.Tinhtoan());
            }        
        }
        else
        {   
            JOptionPane.showMessageDialog(this,"Nhập sai rồi","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_tinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhanSo_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhanSo_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhanSo_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhanSo_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhanSo_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_rg;
    private javax.swing.JButton bt_tinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lb_kq;
    private javax.swing.JTextField txt_ms;
    private javax.swing.JTextField txt_ts;
    // End of variables declaration//GEN-END:variables
}
