/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package S3E4P1;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class PhuongTrinhBN_UI extends javax.swing.JFrame {

    /**
     * Creates new form PhuongTrinhBN_UI
     */
    public PhuongTrinhBN_UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_a = new javax.swing.JTextField();
        txt_b = new javax.swing.JTextField();
        bt_pt = new javax.swing.JButton();
        bt_gpt = new javax.swing.JButton();
        lb_kq = new javax.swing.JLabel();
        lb_pt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phương trình bậc nhất ");
        setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nhập a :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nhập b :");

        txt_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txt_b.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        bt_pt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_pt.setText("Phương Trình");
        bt_pt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ptActionPerformed(evt);
            }
        });

        bt_gpt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_gpt.setText("Giải phương trình");
        bt_gpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_gptActionPerformed(evt);
            }
        });

        lb_kq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_kq.setText("Kết quả :");

        lb_pt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_pt.setText("Phương trình :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_kq)
                    .addComponent(lb_pt)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(bt_pt))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(txt_b)
                                    .addComponent(txt_a)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(bt_gpt)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txt_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_pt)
                    .addComponent(bt_gpt))
                .addGap(27, 27, 27)
                .addComponent(lb_pt)
                .addGap(18, 18, 18)
                .addComponent(lb_kq)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_ptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ptActionPerformed
        // TODO add your handling code here:
        String a = txt_a.getText();
        String b = txt_b.getText();
        
        PhuongTrinhBacNhat pt = new PhuongTrinhBacNhat();
        if (pt.KiemTra(a) && pt.KiemTra(b))
        {
            pt = new PhuongTrinhBacNhat(Integer.parseInt(a),Integer.parseInt(b));
            lb_pt.setText(lb_pt.getText() +"  "+ pt.toString());
        }
        else
        {   
            JOptionPane.showMessageDialog(this,"Nhập sai rồi","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_bt_ptActionPerformed

    private void bt_gptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_gptActionPerformed
        // TODO add your handling code here:
        String a = txt_a.getText();
        String b = txt_b.getText();
        
        PhuongTrinhBacNhat pt = new PhuongTrinhBacNhat();
        if (pt.KiemTra(a) && pt.KiemTra(b))
        {
            if(Integer.parseInt(a) == 0)
            {
                 JOptionPane.showMessageDialog(this,"a phải khác 0","Error",JOptionPane.ERROR_MESSAGE);
            }
             
            else
            {
                  pt = new PhuongTrinhBacNhat(Integer.parseInt(a),Integer.parseInt(b));
                  lb_kq.setText(lb_kq.getText() +"  "+ pt.GiaiPT());
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Nhập sai rồi","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_gptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhuongTrinhBN_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhuongTrinhBN_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhuongTrinhBN_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhuongTrinhBN_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhuongTrinhBN_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_gpt;
    private javax.swing.JButton bt_pt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lb_kq;
    private javax.swing.JLabel lb_pt;
    private javax.swing.JTextField txt_a;
    private javax.swing.JTextField txt_b;
    // End of variables declaration//GEN-END:variables
}
